// <auto-generated />
namespace OOAD_PROJECT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DBINIT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBINIT));
        
        string IMigrationMetadata.Id
        {
            get { return "202212251840191_DBINIT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
